<?xml version="1.0" encoding="utf-8"?><testsuite errors="1" failures="0" name="pytest" skips="0" tests="1" time="0.375"><testcase classname="" file="tests/test_helloworld.py" name="tests.test_helloworld" time="0"><error message="collection failure">tests\test_helloworld.py:5: in &lt;module&gt;
    VALID_DEVICECONNECTIONSTRING = os.environ[&apos;DEVICE_CONNECTION_STRING&apos;]
C:\Python27\lib\os.py:425: in __getitem__
    return self.data[key.upper()]
E   KeyError: &apos;DEVICE_CONNECTION_STRING&apos;</error></testcase></testsuite>